### ISSUE TITLE
avoid switch statement

### ISSUE THREAD

**Issue by holgerdell** [hugo-brito/DynamicIntegerSetsWithOptimalRankSelectPredecessorSearch#1]
https://github.com/hugo-brito/DynamicIntegerSetsWithOptimalRankSelectPredecessorSearch/blob/46ee3c76c23ac9bedcf7efab705198cff1056ef9/src/main/java/BinaryTree.java#L23

Rather than going through the switch statement, you can simply return this value.

**Comment by hugo-brito** [comment]
Fixed! Thank you!
